### PR TITLE
Add weather and boosted types to gym pop-up

### PR DESCRIPTION
**Pull request by wraythex**
Add a weather icon and the associated boosted types underneath the gym's image.  This is a convenient way to see if a raid boss is boosted or not.

## Motivation and Context

This is a convenient way to see if a raid boss is boosted or not.

## How Has This Been Tested?

I've run this change on my server for weeks and it works fine.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ReuschelCGN** [comment]
Nice idea, but I think in static/js/map/map.gym.js line 462 you opened a div, but it is not closed in line 474/475 so it will break the view for gym popup.... will try your commit today!

**Comment by wraythex** [comment]
I did not create the div on 462, I only added a css selector to it.  However, that div is (always has been) properly closed on 474.  I've been running this on my server with no problems.

This should work well for you, too.  I look forward to hearing your results.

**Comment by ReuschelCGN** [comment]
Okay now it worked here in two Maps. TYVM

**Review by na-ji — APPROVED** [review]

**Comment by na-ji** [comment]
Thanks

**Pull request merged**
