### PR TITLE
Add trashcans for non-persistent removal of quests, rocket-stops and raids.

### PR DESCRIPTION
**Pull request by pki0**
## Description

Add trashcans to labels:
- Pokestop (Rocket, Quest)
- Raids (Egg, Bosses)

## Motivation and Context

#161 
## How Has This Been Tested?

Running this for a while on my own map.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by acocalypso** [comment]
This is gold, works perfectly fine.

**Comment by dcooper0591** [comment]
Yes, this is amazing! Thank you so much for doing this!

**Review by na-ji — APPROVED** [review]

**Comment by acocalypso** [comment]
Merge?

**Comment by HELLspawnTIM** [comment]
> Merge?

It is already merged since 25 days

**Pull request merged**
