### PR TITLE
Update updateLabelDiffTime to include days left

### PR DESCRIPTION
**Pull request by JimBim89**
## Description
Added days to the remaining time calculations used in labels.

## Motivation and Context
Some timers like showcases and elite raids have longer diff times.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by wraythex** [comment]
Thanks for this PR.

Why not include the seconds in time remaining when day>0?  I know I would personally prefer to see it.

**Comment by JimBim89** [comment]
I thought it cluttered the tooltip too much and if its up for days you wont care for seconds.

02d07h52m03s
2d07h52m03s
02d07h52m
2d07h52m

Open for discussion though, also do you think the leading 0 is needed for days?

**Comment by wraythex** [comment]
That makes sense. We can leave seconds off when day>0.

And no, I don't think we need a leading 0 on days.

**Comment by JabLuszko** [comment]
Do we really need hours and minutes when there is 3 days 12 hours 30 minutes left on that showcase [ > 1 day, I guess]? I would prefer something along "~3 days" - that will give you all the needed information (longer than day?) on quick glance without making those too tooltips too long? If someone really need to know correct end-time 3 days in advance he can just click the stop to see in popup.

**Comment by JimBim89** [comment]
These are tooltip labels, I don't think rm has marker timers.

**Comment by HELLspawnTIM** [comment]
> Do we really need hours and minutes when there is 3 days 12 hours 30 minutes left on that showcase [ > 1 day, I guess]? I would prefer something along "~3 days" - that will give you all the needed information (longer than day?) on quick glance without making those too tooltips too long? If someone really need to know correct end-time 3 days in advance he can just click the stop to see in popup.

imho it's important to know when the showcase ends, even days before. Because you are able to switch your Pokémon out remotely even minutes before. If you know the exact ending you can set yourself a reminder to do that.

**Comment by wraythex** [comment]
I agree that we should give a detailed, but not too cluttered, status of how long is left on these events.

Unless there are big objections, I'll merge this in a few hours.

**Comment by ofrinach** [comment]
A little note: 
In the _pokestopLabel_ function when switching from _timestampToTime_ to _timestampToDateTime_ it will also add "Today" at the beginning for almost all rocket invasions.
I believe that would really clutter the popup

**Comment by wraythex** [comment]
Good catch, I wouldn't want that to be added to all short term invasions.

JimBim, can you update this PR so that it uses the original "timestampToTime" if  there is less than 24 hours remaining?

**Comment by wraythex** [comment]
Actually, now that I've seen it more, I don't think we need the date at all.  It should be enough that the time remaining says X days remaining.
From this:
2023-09-09 20:00:00 (3d00h00m)
To this:
20:00:00 (3d00h00m)

With this we can always use "timestampToTime".  What does everyone else think about this?

**Comment by JimBim89** [comment]
That's fine for me.

**Comment by wraythex** [comment]
Looks good.  Thanks for the update.

**Pull request merged**
