### PR TITLE
Add showcase support to RM-async

### PR DESCRIPTION
**Pull request by wraythex**
Process showcase info and show it as an incident at stops.  Added it to the incident filter.

## Description

Convert incident_display_type 9 to an invasion number and use that to display showcases at stops.
Added new images for all showcases plus lures and/or quests.

## How Has This Been Tested?

Testing will start when this PR is created.  Feedback welcome from other testers.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by JimBim89** [comment]
Looks good, maybe also add the gold stop (type 7) which are currently active?

**Review by rubendgpedrosa — APPROVED** [review]

**Comment by wraythex** [comment]
Gimmighoul incidents have been added.

**Comment by wraythex** [comment]
Switched incident images to the Gimmighoul coin based on feedback from Discord.  This is ready for more testing now.

**Comment by wraythex** [comment]
I'll create the updated sidebar stats as a separate PR so everyone can weigh in on that separately.

I'll go ahead and merge this one now.

**Pull request merged**
