### PR TITLE
fr.json

### PR DESCRIPTION
**Pull request by ClawOfDead**
All the items and stuff that wasn't well displayed in french is now correctly translated and ordered by alphabetic.

Mons and attacks are together in the first part of the file.

Objects and interface translations are in the end of the file

## How Has This Been Tested?
It just work perfectly fine in my environnement ;)

### CODE REVIEW

**Comment by ClawOfDead** [comment]
Hello,
I checked it’s only because I grouped all the info that were on different places of the file, at least I think. But don’t merge yet I have more to come have to translate the rest. Plus I have some js files to change to due to translation and i8ln added on them. I will do it tonight. 😊

De : Daan Groot ***@***.***>
Envoyé : mardi, 7 février 2023 18:03
À : cecpk/RocketMAD ***@***.***>
Cc : ClawOfDead ***@***.***>; Author ***@***.***>
Objet : Re: [cecpk/RocketMAD] fr.json (PR #272)


Hi, there are some merge conflicts. Could you resolve them? :)

**Comment by ClawOfDead** [comment]
Oh and I forgot someone changed the variable “values” to “stats” that’s why some are deleted. 😉

De : Daan Groot ***@***.***>
Envoyé : mardi, 7 février 2023 18:03
À : cecpk/RocketMAD ***@***.***>
Cc : ClawOfDead ***@***.***>; Author ***@***.***>
Objet : Re: [cecpk/RocketMAD] fr.json (PR #272)


Hi, there are some merge conflicts. Could you resolve them? :)

**Comment by wraythex** [comment]
Is this PR needed anymore since you created PR 277 which also updates fr.json?

**Comment by wraythex** [comment]
Since PR 277 also updated fr.json, I'll close this PR.  If any updates are still needed feel free to open a new PR.

**Pull request closed without merging**
