### PR TITLE
Add primal raids (async)

### PR DESCRIPTION
**Pull request by wraythex**
Add primal raid icon file and related code to add primal raids (level 10) to RM:async

## How Has This Been Tested?

Tested on local server, works well

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by JabLuszko** [comment]
This also need an update to `rocketmad/dyn_img.py` - evolution 4 is new and it won't load Kyogre/Groudon icons.

```
--- a/rocketmad/dyn_img.py
+++ b/rocketmad/dyn_img.py
@@ -33,11 +33,13 @@ EVOLUTION_UNSET = 0
 EVOLUTION_MEGA = 1
 EVOLUTION_MEGA_X = 2
 EVOLUTION_MEGA_Y = 3
+EVOLUTION_PRIMAL = 4

 evolution_suffixes = {
     EVOLUTION_MEGA: "MEGA",
     EVOLUTION_MEGA_X: "MEGA_X",
-    EVOLUTION_MEGA_Y: "MEGA_Y"
+    EVOLUTION_MEGA_Y: "MEGA_Y",
+    EVOLUTION_PRIMAL: "PRIMAL"
 }
```

On top of that we need `PRIMAL` somewhere in raid popup - so it will say `PRIMAL Groudon` rather than just `Groudon` but too lazy for that now.

**Comment by wraythex** [comment]
Thanks for that.  I've added those lines, but I'm not sure how to make sure it picks the primal groudon image when showing the raid info or how to make sure it will say primal in the name.  This should get the primal raid egg and basic groudon/kyogre images on the map though.

**Comment by FimoJones** [comment]
Search for references to 'evolutionId' in the following files and update the case-switch statements to accommodate the `PRIMAL` naming convention.
```
static/dist/js/pokemon-history.built.js
static/dist/js/quest.built.js
static/dist/js/map.concat.js
static/dist/js/quest.concat.js
static/dist/js/map.built.js
static/dist/js/pokemon-history.concat.js
static/js/utils/utils.pokemon.js
```

**Comment by wraythex** [comment]
The dist files are destroyed/created by the npm run build process, can't edit those.  I think as long as "evolution" is set to 4 in the raid db table then the above change will show Primal correctly.

**Comment by FimoJones** [comment]
Yeah, my bad. I know better than to `grep` the result of a `find` on a production server and yet... I've edited the relevant location above.

**Pull request merged**
