### PR TITLE
Add 2 scripts to 1-show, 2-delete, raid/spawn images generated from the substitution pokemon

### PR DESCRIPTION
**Pull request by wraythex**
## Description

I've added two linux shell scripts into the <rocketmad>/static/images/ directory that can be used to list, or delete, raid and spawn images that were dynamically generated from the substitution pokemon (ie, before their assets had been downloaded locally).

## Motivation and Context

This is a quick way to remove just the icons generated with the substitution pokemon, and not all icons.  It's good to have a quick way to remove the substitution pokemon when the correct assets have been downloaded locally so the map can generate/show the correct image.  Also, I like not deleting all pokemon icons so that RM doesn't have to generate them all again.

## How Has This Been Tested?

I've run the scripts and was able to see when substitution icons had been generated, and could easily remove them.  Also, if there are none, then nothing is shown, or deleted.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by na-ji — CHANGES_REQUESTED** [review]
Could you add a shebang and the script shell extension? Otherwise those are great script!

**Comment by wraythex** [comment]
Added!  Thanks for taking a look.

**Comment by FimoJones** [comment]
I would suggest moving them to the handy 'scripts' directory in the root of the distribution. Leave the 'static' directory alone.

**Comment by wraythex** [comment]
@na-ji Do you want these scripts moved to the scripts directory?

**Comment by wraythex** [comment]
@daangroot Do you have a preference where these scripts reside?

**Pull request merged**
